[2025-07-23T22:09:22.286-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [queued]>
[2025-07-23T22:09:22.299-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [queued]>
[2025-07-23T22:09:22.300-0400] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-23T22:09:22.316-0400] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_and_upload_to_minio> on 2025-07-24 02:03:22.329965+00:00
[2025-07-23T22:09:22.323-0400] {standard_task_runner.py:60} INFO - Started process 413 to run task
[2025-07-23T22:09:22.329-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_csv_pipeline', 'extract_and_upload_to_minio', 'manual__2025-07-24T02:03:22.329965+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_local_dag.py', '--cfg-path', '/tmp/tmp84jwesq9']
[2025-07-23T22:09:22.333-0400] {standard_task_runner.py:88} INFO - Job 13: Subtask extract_and_upload_to_minio
[2025-07-23T22:09:22.426-0400] {task_command.py:423} INFO - Running <TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [running]> on host a253e541d1df
[2025-07-23T22:09:22.531-0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='etl_local_csv_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_upload_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T02:03:22.329965+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T02:03:22.329965+00:00'
[2025-07-23T22:09:24.545-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:09:24.774-0400] {etl_local_dag.py:127} INFO - File 2019-PT1.csv loaded with 148777 rows and 53 columns
[2025-07-23T22:09:28.226-0400] {etl_local_dag.py:150} ERROR - Error processing 2019-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:09:29.719-0400] {etl_local_dag.py:127} INFO - File 2019-PT2.csv loaded with 74548 rows and 53 columns
[2025-07-23T22:09:31.483-0400] {etl_local_dag.py:150} ERROR - Error processing 2019-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:09:34.712-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:09:35.249-0400] {etl_local_dag.py:127} INFO - File 2020-PT1.csv loaded with 140414 rows and 53 columns
[2025-07-23T22:09:40.051-0400] {etl_local_dag.py:150} ERROR - Error processing 2020-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:09:42.115-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:09:42.271-0400] {etl_local_dag.py:127} INFO - File 2020-PT2.csv loaded with 77740 rows and 53 columns
[2025-07-23T22:09:45.484-0400] {etl_local_dag.py:150} ERROR - Error processing 2020-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:09:48.658-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:09:48.866-0400] {etl_local_dag.py:127} INFO - File 2021-PT1.csv loaded with 151096 rows and 53 columns
[2025-07-23T22:09:53.137-0400] {etl_local_dag.py:150} ERROR - Error processing 2021-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:09:53.883-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:09:53.945-0400] {etl_local_dag.py:127} INFO - File 2021-PT2.csv loaded with 73173 rows and 53 columns
[2025-07-23T22:09:55.600-0400] {etl_local_dag.py:150} ERROR - Error processing 2021-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:09:58.729-0400] {etl_local_dag.py:127} INFO - File 2022-PT1.csv loaded with 159321 rows and 53 columns
[2025-07-23T22:10:02.825-0400] {etl_local_dag.py:150} ERROR - Error processing 2022-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:10:03.933-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:10:04.020-0400] {etl_local_dag.py:127} INFO - File 2022-PT2.csv loaded with 70925 rows and 53 columns
[2025-07-23T22:10:05.703-0400] {etl_local_dag.py:150} ERROR - Error processing 2022-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:10:08.083-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (5,46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:10:08.300-0400] {etl_local_dag.py:127} INFO - File 2023-PT1.csv loaded with 147288 rows and 53 columns
[2025-07-23T22:10:11.690-0400] {etl_local_dag.py:150} ERROR - Error processing 2023-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:10:12.776-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:10:12.849-0400] {etl_local_dag.py:127} INFO - File 2023-PT2.csv loaded with 71409 rows and 53 columns
[2025-07-23T22:10:14.513-0400] {etl_local_dag.py:150} ERROR - Error processing 2023-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:10:14.521-0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_local_dag.py", line 154, in extract_and_upload_to_minio
    raise ValueError("No files were successfully uploaded")
ValueError: No files were successfully uploaded
[2025-07-23T22:10:14.549-0400] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_local_csv_pipeline, task_id=extract_and_upload_to_minio, execution_date=20250724T020322, start_date=20250724T020922, end_date=20250724T021014
[2025-07-23T22:10:14.573-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task extract_and_upload_to_minio (No files were successfully uploaded; 413)
[2025-07-23T22:10:14.612-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-23T22:10:14.650-0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
