[2025-07-23T22:03:26.254-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [queued]>
[2025-07-23T22:03:26.270-0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [queued]>
[2025-07-23T22:03:26.271-0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T22:03:26.297-0400] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_and_upload_to_minio> on 2025-07-24 02:03:22.329965+00:00
[2025-07-23T22:03:26.306-0400] {standard_task_runner.py:60} INFO - Started process 260 to run task
[2025-07-23T22:03:26.314-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_csv_pipeline', 'extract_and_upload_to_minio', 'manual__2025-07-24T02:03:22.329965+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_local_dag.py', '--cfg-path', '/tmp/tmp1j68gjte']
[2025-07-23T22:03:26.319-0400] {standard_task_runner.py:88} INFO - Job 10: Subtask extract_and_upload_to_minio
[2025-07-23T22:03:26.411-0400] {task_command.py:423} INFO - Running <TaskInstance: etl_local_csv_pipeline.extract_and_upload_to_minio manual__2025-07-24T02:03:22.329965+00:00 [running]> on host a253e541d1df
[2025-07-23T22:03:26.524-0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='etl_local_csv_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_upload_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T02:03:22.329965+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T02:03:22.329965+00:00'
[2025-07-23T22:03:29.332-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:03:29.676-0400] {etl_local_dag.py:127} INFO - File 2019-PT1.csv loaded with 148777 rows and 53 columns
[2025-07-23T22:03:35.688-0400] {etl_local_dag.py:150} ERROR - Error processing 2019-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:03:37.471-0400] {etl_local_dag.py:127} INFO - File 2019-PT2.csv loaded with 74548 rows and 53 columns
[2025-07-23T22:03:40.981-0400] {etl_local_dag.py:150} ERROR - Error processing 2019-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:03:43.644-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:03:43.852-0400] {etl_local_dag.py:127} INFO - File 2020-PT1.csv loaded with 140414 rows and 53 columns
[2025-07-23T22:03:47.812-0400] {etl_local_dag.py:150} ERROR - Error processing 2020-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:03:49.216-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:03:49.303-0400] {etl_local_dag.py:127} INFO - File 2020-PT2.csv loaded with 77740 rows and 53 columns
[2025-07-23T22:03:51.210-0400] {etl_local_dag.py:150} ERROR - Error processing 2020-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:03:53.585-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:03:54.009-0400] {etl_local_dag.py:127} INFO - File 2021-PT1.csv loaded with 151096 rows and 53 columns
[2025-07-23T22:03:58.226-0400] {etl_local_dag.py:150} ERROR - Error processing 2021-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:03:59.796-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:03:59.878-0400] {etl_local_dag.py:127} INFO - File 2021-PT2.csv loaded with 73173 rows and 53 columns
[2025-07-23T22:04:01.711-0400] {etl_local_dag.py:150} ERROR - Error processing 2021-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:04:04.153-0400] {etl_local_dag.py:127} INFO - File 2022-PT1.csv loaded with 159321 rows and 53 columns
[2025-07-23T22:04:08.218-0400] {etl_local_dag.py:150} ERROR - Error processing 2022-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:04:09.358-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:04:09.455-0400] {etl_local_dag.py:127} INFO - File 2022-PT2.csv loaded with 70925 rows and 53 columns
[2025-07-23T22:04:11.046-0400] {etl_local_dag.py:150} ERROR - Error processing 2022-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:04:13.638-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (5,46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:04:13.912-0400] {etl_local_dag.py:127} INFO - File 2023-PT1.csv loaded with 147288 rows and 53 columns
[2025-07-23T22:04:17.688-0400] {etl_local_dag.py:150} ERROR - Error processing 2023-PT1.csv: read() must return 'bytes' object
[2025-07-23T22:04:19.084-0400] {logging_mixin.py:188} WARNING - /opt/airflow/dags/etl_local_dag.py:123 DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-07-23T22:04:19.174-0400] {etl_local_dag.py:127} INFO - File 2023-PT2.csv loaded with 71409 rows and 53 columns
[2025-07-23T22:04:21.035-0400] {etl_local_dag.py:150} ERROR - Error processing 2023-PT2.csv: read() must return 'bytes' object
[2025-07-23T22:04:21.052-0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_local_dag.py", line 154, in extract_and_upload_to_minio
    raise ValueError("No files were successfully uploaded")
ValueError: No files were successfully uploaded
[2025-07-23T22:04:21.081-0400] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_csv_pipeline, task_id=extract_and_upload_to_minio, execution_date=20250724T020322, start_date=20250724T020326, end_date=20250724T020421
[2025-07-23T22:04:21.105-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task extract_and_upload_to_minio (No files were successfully uploaded; 260)
[2025-07-23T22:04:21.156-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-23T22:04:21.197-0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
